version: "3.8"
services:
  deno:
    build:
      context: ./
      dockerfile: Dockerfile
    volumes:
      - type: volume
        source: deno
        target: /app
    ports:
      - "${DENO_PORT-:6500}:${DENO_PORT:-6500}"
    depends_on:
      - db
  db:
    image: mongo:latest
    environment:
      - MONGO_INITDB_DB=deno_db
      - MONGO_INITDB_ROOT_USERNAME=deno
      - MONGO_INITDB_ROOT_PASSWORD=deno
    volumes:
      - /mongo/db:/mongo/db
    ports:
      - 27017:27017
volumes:
  deno:
  mongo:
    name: "deno_mongo"
